version: "3.8"

services:
  mainapi:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
    ports:
      - "8090:8080"
    depends_on:
      - sqlserver
    env_file:
      - .env

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1431:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - sql-server-volume:/var/opt/mssql

volumes:
  sql-server-volume:
    external: false # set to false if you want Docker Compose to create a new volume
